baseURL = 'https://rjma.dev/'
languageCode = 'en-us'
title = 'rjma'
theme = 'blog'

[permalinks]
posts = "/posts/:slug/"

[markup]
  [markup.highlight]
    noClasses = false          # Use CSS classes, not inline styles
    lineNos = false            # Enable line numbers? (optional)